
usuario {
	id_usuario integer pk increments unique
	email varchar(40)
	senha_hash varchar(255)
	tipo_usuario varchar(20)
	data_registro timestamp
}

categorias {
	id_categoria integer pk increments unique
	nome varchar(30)
	descricao varchar(50)
}

turmas {
	id_turma integer pk increments unique
	nome varchar(30)
	descricao varchar(50)
}

atleta {
	id_atleta integer pk increments unique
	usuario_id integer > usuario.id_usuario
	nome varchar(30)
	data_nascimento date
	sexo varchar(20)
	rg varchar(30)
	cpf varchar(30)
	telefone varchar(20)
	responsavel varchar(40)
	federado boolean
	ativo boolean
	categoria_id integer > categorias.id_categoria
	turma_id integer > turmas.id_turma
	data_criacao timestamp
}

treinador {
	id_treinador integer pk increments unique
	usuario_id integer > usuario.id_usuario
	nome varchar(40)
	telefone varchar(20)
	data_criacao timestamp
}

tipo_treino {
	id_tipo_treino integer pk increments unique
	nome varchar(30)
	descricao varchar(50)
}

treino {
	id_treino integer pk increments unique
	treinador_id integer > treinador.id_treinador
	tipo_treino_id integer > tipo_treino.id_tipo_treino
	data_treino date
	carga_treino varchar(30)
	metragem varchar(20)
	observacao text
	data_criacao timestamp
}

treino_atleta {
	id_treino_atleta integer pk increments unique
	treino_id integer > treino.id_treino
	atleta_id integer > atleta.id_atleta
	status varchar(20)
	observacao varchar(100)
}

presenca {
	id_presenca integer pk increments unique
	atleta_id integer > atleta.id_atleta
	treino_id integer > treino.id_treino
	status varchar(30)
	observacao text
	data_criacao timestamp
}

prova {
	id_prova integer pk increments unique
	nome varchar(30)
	distancia varchar(30)
	estilo varchar(30)
}

tipo_teste {
	id_tipo_teste integer pk increments unique
	nome varchar(30)
	unidade varchar(20)
	descricao varchar(50)
}

resultado_teste {
	id_resultado_teste integer pk increments unique
	atleta_id integer > atleta.id_atleta
	tipo_teste_id integer > tipo_teste.id_tipo_teste
	prova_id integer > prova.id_prova
	valor decimal
	data_resultado date
	observacao text
	data_criacao timestamp
}

